In [1]:
# Loading Data and Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Lasso, LogisticRegression, ElasticNet, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
# Reading and viewing CVSs
train = pd.read_csv("Resources/train.csv")
train

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
# Dropping 'Id' column
train.drop("Id", axis = 1, inplace = True)
train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [4]:
# Cleaning up data (string columns with None and integer columns with 0)
train["PoolQC"] = train["PoolQC"].fillna("None")
train["MiscFeature"] = train["MiscFeature"].fillna("None")
train["Alley"] = train["Alley"].fillna("None")
train["Fence"] = train["Fence"].fillna("None")
train["FireplaceQu"] = train["FireplaceQu"].fillna("None")
train["LotFrontage"] = train.groupby("Neighborhood")["LotFrontage"].transform(lambda x: x.fillna(x.median()))
for col in ('GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'):
    train[col] = train[col].fillna('None')
for col in ('GarageYrBlt', 'GarageArea', 'GarageCars'):
    train[col] = train[col].fillna(0)
for col in ('BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF','TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath'):
    train[col] = train[col].fillna(0)
for col in ('BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2'):
    train[col] = train[col].fillna('None')
train["MasVnrType"] = train["MasVnrType"].fillna("None")
train["MasVnrArea"] = train["MasVnrArea"].fillna(0)
train['MSZoning'] = train['MSZoning'].fillna(train['MSZoning'].mode()[0])
train = train.drop(['Utilities'], axis=1)
train["Functional"] = train["Functional"].fillna("Typ")
train['Electrical'] = train['Electrical'].fillna(train['Electrical'].mode()[0])
train['KitchenQual'] = train['KitchenQual'].fillna(train['KitchenQual'].mode()[0])
train['Exterior1st'] = train['Exterior1st'].fillna(train['Exterior1st'].mode()[0])
train['Exterior2nd'] = train['Exterior2nd'].fillna(train['Exterior2nd'].mode()[0])
train['SaleType'] = train['SaleType'].fillna(train['SaleType'].mode()[0])
train['MSSubClass'] = train['MSSubClass'].fillna("None")
train

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,LotConfig,LandSlope,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,None,Reg,Lvl,Inside,Gtl,...,0,None,None,None,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,None,Reg,Lvl,FR2,Gtl,...,0,None,None,None,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,None,IR1,Lvl,Inside,Gtl,...,0,None,None,None,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,None,IR1,Lvl,Corner,Gtl,...,0,None,None,None,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,None,IR1,Lvl,FR2,Gtl,...,0,None,None,None,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,Pave,None,Reg,Lvl,Inside,Gtl,...,0,None,None,None,0,8,2007,WD,Normal,175000
1456,20,RL,85.0,13175,Pave,None,Reg,Lvl,Inside,Gtl,...,0,None,MnPrv,None,0,2,2010,WD,Normal,210000
1457,70,RL,66.0,9042,Pave,None,Reg,Lvl,Inside,Gtl,...,0,None,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,20,RL,68.0,9717,Pave,None,Reg,Lvl,Inside,Gtl,...,0,None,None,None,0,4,2010,WD,Normal,142125
1459,20,RL,75.0,9937,Pave,None,Reg,Lvl,Inside,Gtl,...,0,None,None,None,0,6,2008,WD,Normal,147500

In [5]:
# Getting dummies for string based columns
train = pd.get_dummies(train)
train

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,0,0,0,1,0,0,0,0,1,0
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,0,0,0,1,0,0,0,0,1,0
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,0,0,0,1,0,0,0,0,1,0
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,0,0,0,1,0,0,0,0,1,0

In [6]:
# Setting up x(target) and y(data) values
# Independent variable (dataframe)
x = train.drop(columns=['SalePrice'])
# Dependent variable (series)
y = train['SalePrice'].values.reshape(-1,1)
print(x.shape, y.shape)

(1460, 300) (1460, 1)

In [7]:
# Splitting data into test and train
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)

In [8]:
# Creating scaler
x_scaler = StandardScaler().fit(x_train)
y_scaler = StandardScaler().fit(y_train)

In [9]:
# Transforming with scaler
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)
y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

In [10]:
# Creating empty regular linear regression model
regressor = LinearRegression()
# Training model
regressor.fit(x_train_scaled, y_train_scaled)
# Making predictions on test portion
reg_predictions = regressor.predict(x_test_scaled)
reg_MSE = mean_squared_error(y_test_scaled, reg_predictions)
r2_reg = regressor.score(x_test_scaled, y_test_scaled)
print(f"Regular Mean Squared Error: {reg_MSE}, Regular Linear Score: {r2_reg}")

Regular Mean Squared Error: 6.468112512446369e+25, Regular Linear Score: -5.605861201088467e+25

In [11]:
# Training lasso linear regression model
lasso = Lasso(alpha=.01).fit(x_train_scaled, y_train_scaled)
# Making predictions on test portion
predictions = lasso.predict(x_test_scaled)
MSE = mean_squared_error(y_test_scaled, predictions)
r2_las = lasso.score(x_test_scaled, y_test_scaled)
print(f"Lasso Mean Squared Error: {MSE}, Lasso Score: {r2_las}")

Lasso Mean Squared Error: 0.11198392620528083, Lasso Score: 0.9029444299474153

In [12]:
# Creating empty random forest regression model
rf = RandomForestRegressor(n_estimators=200)
# Training random forest regression model
rf = rf.fit(x_train, y_train)
# Making predictions on test portion
rf_predictions = rf.predict(x_test_scaled)
rf_MSE = mean_squared_error(y_test_scaled, rf_predictions)
r2_rf = rf.score(x_test, y_test)
print(f"Random Forest Mean Squared Error: {rf_MSE}, Random Forest Score: {r2_rf}")

C:\Users\pamhi\anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

Random Forest Mean Squared Error: 4093169485.868983, Random Forest Score: 0.8924218142052752

In [13]:
# Training ridge linear regression model
ridge = Ridge(alpha=.01).fit(x_train_scaled, y_train_scaled)
# Making predictions on test portion
ridge_predictions = ridge.predict(x_test_scaled)
ridge_MSE = mean_squared_error(y_test_scaled, ridge_predictions)
r2_ridge = ridge.score(x_test_scaled, y_test_scaled)
print(f"Ridge Mean Squared Error: {ridge_MSE}, Ridge Score: {r2_ridge}")

Ridge Mean Squared Error: 0.5314679747086739, Ridge Score: 0.5393809719129983

In [14]:
# Training elastic net linear regression model
en = ElasticNet(alpha=.01).fit(x_train_scaled, y_train_scaled)
# Making predictions on test portion
en_predictions = en.predict(x_test_scaled)
en_MSE = mean_squared_error(y_test_scaled, en_predictions)
r2_en = en.score(x_test_scaled, y_test_scaled)
print(f"Elastic Net Mean Squared Error: {en_MSE}, Elastic Net Score: {r2_en}")

Elastic Net Mean Squared Error: 0.1119869652540367, Elastic Net Score: 0.9029417960282502

In [15]:
# Lasso is slightly better than Elastic Net so it will be chosen to continue
# Inversing scaling on y
predictions = y_scaler.inverse_transform(predictions)
predictions

array([148393.82114147, 347809.50100843,  96722.26069262, 168137.67632608,
       329083.88596242,  67212.12802028, 226046.74134092, 140023.60195975,
        60461.31903823, 138348.18087433, 142482.99110059, 109299.2212298 ,
        95114.2207917 , 214841.26135097, 174047.67141066, 128022.88550453,
       193488.17486018, 131858.6511305 , 123289.00161286, 214300.72524759,
       155905.43474898, 206592.38445656, 175419.5410394 , 123297.71182395,
       202508.86968095, 147352.55681164, 199406.39971571,  98957.15865461,
       173769.56711842, 217498.08088464, 121658.18049414, 263704.22841   ,
       238749.59942329, 105611.63381192, 235079.02149958, 152845.10313446,
       135449.76910182, 204194.30075427, 310659.57544884, 106673.89209417,
       127786.72370494, 228463.76731429, 110738.5104073 , 367803.1054551 ,
       129891.04360621, 154516.44024207,  98975.93373136, 131300.0614023 ,
       411969.05066003, 130875.62950369, 113503.73114918, 235463.10863629,
       114939.64567602, 286177.01680524, 154210.20607787, 237893.28377831,
       201775.75079275, 177382.8725336 , 142616.32208873,  96060.54958107,
        58754.57639522, 162561.09918213, 307891.17677889, 263268.97352106,
       299806.34243045, 213277.12968017,  99234.65071536, 288792.58020193,
       110005.74436189, 168975.27476729, 126561.82382403, 124380.40829638,
       102412.85556293,  56691.33297446, 445869.67834801, 191727.13754616,
       306476.56829213, 335309.09312737, 141785.54155775, 121744.46433169,
       113742.49138374,  70472.72107706, 114380.29955032,  86743.82010819,
       157042.36786293, 138859.39753197, 258597.46101234, 207858.19048556,
       140467.28654023, 193071.92753901, 148139.98949567, 141087.12703277,
       142708.88908494, 271081.77063964, 125334.8207149 , 183540.4996163 ,
       201348.1530951 , 177991.8674282 , 216856.34637346, 262886.10379538,
       176139.48995106, 205990.81924994, 289097.16239675, 131821.09685113,
       199443.08222923, 176086.33442984, 147948.94951015, 286723.71005432,
       150599.25729566, 204760.1285948 ,  34484.33870418, 131168.16932618,
       140090.36840919, 141173.18062181, 205013.11939184, 113796.40960346,
       100715.06979328, 103154.14154819, 130587.2164067 , 284134.40976725,
       126661.09718319, 141223.14695663, 181398.70963844, 176978.08762441,
       191634.52758806, 128077.87165981, 230662.65666171,  90896.06276146,
       144462.37017049, 184252.91974314, 189887.32949273, 336676.78443687,
       197344.76812373, 145554.69440128,  33129.78492321, 375161.99295879,
       362977.36471784, 134039.68261696, 229838.08407127, 571218.33887897,
       346949.96950858, 122725.89776964, 178424.96459674, 165061.59996419,
       131539.9617576 , 120198.99150343, 229909.53408887, 194931.80130216,
       125640.18238957,  54683.2413889 , 120052.16456773, 140699.50599367,
       267513.32729779, 160491.25366853,  77179.88503864, 120816.13632055,
       132845.4724281 , 149146.12780904,  78326.29301871, 133082.63715514,
       212313.10886879, 127262.90039397, 291552.83336042, 152966.02146803,
       111740.04540257, 135297.81972921, 246225.74158811, 333139.80503012,
       410393.32380762, 215486.52104615, 363829.02339448,  87310.09110105,
       113129.0442048 , 142607.19451052, 318529.67051918, 114022.26005449,
       121906.55994817, 218166.4056938 , 125616.75504932, 171559.54588284,
       194330.20396037, 124155.48520721, 124708.97326933, 155373.78378064,
       244396.13924156, 138591.40853041, 253148.01373221, 219874.01812469,
       204624.65156211,  79853.46508509, 114688.43523325, 103877.5885021 ,
       146498.18686682, 147161.32116171, 200452.23516865, 210057.67980082,
       197391.53577502,  98034.12448482, 204611.87026476, 131611.76996914,
       260064.52386007, 215271.33563939, 121587.23793478, 310750.20725439,
       196697.47663241, 117627.74380528, 226881.50183129, 133303.62158321,
       154729.98152205, 104132.7490919 , 222559.94853559, 144848.31570656,
       113198.77218104, 163426.55162851, 204771.01170567, 245028.81856599,
       214849.10918176, 147709.40780045, 128960.35227997, 123519.90869244,
       130397.20274461, 214328.95704678, 218103.37785849,  89204.11956743,
       216490.52708831, 145256.30292118,  81681.73280828,  92856.37178352,
       168525.54216975, 101230.51403985,  95769.44079139, 170334.22439881,
       118990.40426574, 132284.77725974, 224568.8233214 , 140314.98383045,
       202298.62691168, 162904.88081039, 247820.35664139, 114252.48145754,
       107067.17771369, 252938.51580054, 212314.80895544, 443746.53863684,
       190900.02610986, 134448.71756349, 162380.44034584, 171276.79864256,
       136749.80164597, 102978.54484649, 180617.40595218, 164531.24991634,
       137072.25495071, 103791.70039504, 139719.39212411, 128530.50421867,
       119593.78757121, 115547.3811141 , 175161.67099445, 245915.01766677,
       285571.8688425 , 175385.10199321, 126012.76274687, 246337.66149753,
       340275.99874387, 220970.99032652, 184073.97741176, 136728.92336398,
       109697.77688667, 170381.98353361, 413902.65721216, 225298.35136254,
       231629.76413379,  89587.63851145,  84668.9483636 , 141229.15523104,
       154194.46998105, 331396.05579114, 260544.91591389, 133466.48826821,
       205498.49988476, 107091.37233255, 208965.71203948, 109705.92364457,
       297527.60648967, 180441.73256911, 212662.84585991, 139118.51647796,
       286731.58692583, 193769.22951265, 111288.94703861, 109913.79979954,
       146123.04797875, 171041.28337454,  75402.63568076, 160033.01106725,
       161199.27306111, 134644.63555728, 186794.25315383, 119364.43676213,
       183481.59390905, 227372.6123598 , 125834.72352755, 143305.89092037,
       176443.0246832 , 206677.37388887, 145880.22786128, 213926.09662689,
       230238.31653828, 122580.94837164, 150755.11466709, 188981.37648929,
        97253.39031496, 195475.00942484, 134751.82374215, 179984.14361603,
       186260.95041703, 172796.63199728, 304271.55124387,  61278.62492492,
       230686.83199608, 140360.95488696, 126464.29364925,  89901.55999878,
       199896.63212898, 152906.79361716, 139619.3905606 , 211642.66290815,
       168565.45391757,  84956.34140141, 152935.23471375, 158105.33294975,
       132442.70826277, 209143.40608595, 162659.96760113, 113716.91872091,
       144653.65677447,  83402.06879767,  83692.49485661, 212802.52341848,
       176216.55628907, 130811.02779184, 125456.92494271, 177095.55263243,
       229337.78082909, 349580.18383361, 368437.34839702, 108844.41561156,
       242817.53241271, 136691.01510425, 277464.97344709, 366254.03151531,
       289703.34354212, 183917.78444979, 227805.65193253, 147339.31942224,
       122069.83622599,  83292.71653649, 211029.02988654, 339579.95105063,
       190630.70390659, 118948.09141295, 236239.64163459, 259203.00406854,
       118991.79648233])

In [16]:
# Reducing y_test from list of lists to just a list
y_test_ravel = np.ravel(y_test)

In [17]:
# Turning raveled predictions and y_test_scaled into a dataframe to evaluate
preds_tv = pd.DataFrame({"predictions": predictions,"true values": y_test_ravel})
preds_tv

       predictions  true values
0    148393.821141       154500
1    347809.501008       325000
2     96722.260693       115000
3    168137.676326       159000
4    329083.885962       315500
..             ...          ...
360  190630.703907       195000
361  118948.091413       120000
362  236239.641635       228500
363  259203.004069       248000
364  118991.796482       124000

[365 rows x 2 columns]

In [18]:
# Labeling index to match columns in tableau
preds_tv.rename_axis(index='Id', inplace=True)
preds_tv

       predictions  true values
Id
0    148393.821141       154500
1    347809.501008       325000
2     96722.260693       115000
3    168137.676326       159000
4    329083.885962       315500
..             ...          ...
360  190630.703907       195000
361  118948.091413       120000
362  236239.641635       228500
363  259203.004069       248000
364  118991.796482       124000

[365 rows x 2 columns]

In [19]:
# Saving to csv for tableau
preds_tv.to_csv('Output/predictions_vs_true_values.csv', index = True)

In [20]:
# Listing variables and their scores in descending order
lasso_scores = sorted(list(zip(x_train, lasso.coef_)),reverse=True)
lasso_scores

[('YrSold', 0.0),
 ('YearRemodAdd', 0.030861170087827718),
 ('YearBuilt', 0.08934640382350317),
 ('WoodDeckSF', 0.019226227857973687),
 ('TotalBsmtSF', 0.08340174171828263),
 ('TotRmsAbvGrd', 0.0006513975506880858),
 ('Street_Pave', 1.6222436889500004e-18),
 ('Street_Grvl', -0.0009838212814519054),
 ('ScreenPorch', 0.01777972329932037),
 ('SaleType_WD', -0.0),
 ('SaleType_Oth', 0.0),
 ('SaleType_New', 0.0),
 ('SaleType_ConLw', -0.0),
 ('SaleType_ConLI', -0.0),
 ('SaleType_ConLD', 0.0),
 ('SaleType_Con', 0.006325406239965981),
 ('SaleType_CWD', 0.0),
 ('SaleType_COD', -0.0),
 ('SaleCondition_Partial', 0.04970214517250172),
 ('SaleCondition_Normal', 0.0),
 ('SaleCondition_Family', -0.0032235401222167038),
 ('SaleCondition_Alloca', 0.013086206907631412),
 ('SaleCondition_AdjLand', 0.0),
 ('SaleCondition_Abnorml', -0.014776873214665464),
 ('RoofStyle_Shed', 0.0),
 ('RoofStyle_Mansard', 0.00035809738817386174),
 ('RoofStyle_Hip', 0.0),
 ('RoofStyle_Gambrel', 0.0),
 ('RoofStyle_Gable', -0.005140792925582714),
 ('RoofStyle_Flat', 0.0),
 ('RoofMatl_WdShngl', 0.017944736095962872),
 ('RoofMatl_WdShake', 0.0),
 ('RoofMatl_Tar&Grv', -0.0),
 ('RoofMatl_Roll', 0.0),
 ('RoofMatl_Metal', 0.0),
 ('RoofMatl_Membran', 0.0),
 ('RoofMatl_CompShg', -0.0),
 ('RoofMatl_ClyTile', -0.21114074976447833),
 ('PoolQC_None', -0.0),
 ('PoolQC_Gd', 0.0),
 ('PoolQC_Fa', -0.0),
 ('PoolQC_Ex', 0.04432199775695464),
 ('PoolArea', 0.004829646642966427),
 ('PavedDrive_Y', 0.0),
 ('PavedDrive_P', -0.0),
 ('PavedDrive_N', 0.0),
 ('OverallQual', 0.1414650763746384),
 ('OverallCond', 0.05206685205048621),
 ('OpenPorchSF', 0.0),
 ('Neighborhood_Veenker', 0.008606041077717548),
 ('Neighborhood_Timber', -0.0),
 ('Neighborhood_StoneBr', 0.06055479295802418),
 ('Neighborhood_Somerst', 0.018816328395668682),
 ('Neighborhood_SawyerW', 0.0),
 ('Neighborhood_Sawyer', 0.0),
 ('Neighborhood_SWISU', -0.0),
 ('Neighborhood_OldTown', -0.0),
 ('Neighborhood_NridgHt', 0.05516558304263759),
 ('Neighborhood_NoRidge', 0.07084825529465423),
 ('Neighborhood_NWAmes', -0.0022950735835684396),
 ('Neighborhood_NPkVill', 0.00023264755708860598),
 ('Neighborhood_NAmes', -0.009873338217517975),
 ('Neighborhood_Mitchel', -0.013510330139938923),
 ('Neighborhood_MeadowV', -0.0),
 ('Neighborhood_IDOTRR', -0.0),
 ('Neighborhood_Gilbert', -0.0),
 ('Neighborhood_Edwards', -0.010273186242097934),
 ('Neighborhood_Crawfor', 0.036900928335450695),
 ('Neighborhood_CollgCr', 0.0),
 ('Neighborhood_ClearCr', 0.0),
 ('Neighborhood_BrkSide', 0.011346625615299711),
 ('Neighborhood_BrDale', 0.0),
 ('Neighborhood_Blueste', -0.0),
 ('Neighborhood_Blmngtn', 0.0),
 ('MoSold', -0.0027762940362387727),
 ('MiscVal', -0.0),
 ('MiscFeature_TenC', -0.0),
 ('MiscFeature_Shed', -0.0),
 ('MiscFeature_Othr', 0.0),
 ('MiscFeature_None', 0.0),
 ('MiscFeature_Gar2', -0.0),
 ('MasVnrType_Stone', 0.0),
 ('MasVnrType_None', 0.0),
 ('MasVnrType_BrkFace', -0.0027855794926379424),
 ('MasVnrType_BrkCmn', -0.0012889964045866406),
 ('MasVnrArea', 0.020068144035938398),
 ('MSZoning_RM', -0.012100020930473781),
 ('MSZoning_RL', 0.0),
 ('MSZoning_RH', -0.0),
 ('MSZoning_FV', 0.012556750926695963),
 ('MSZoning_C (all)', -0.004979211646367425),
 ('MSSubClass', -0.02193123408363685),
 ('LowQualFinSF', -0.0069540786656051),
 ('LotShape_Reg', -0.0),
 ('LotShape_IR3', 0.0),
 ('LotShape_IR2', 0.013260116307651707),
 ('LotShape_IR1', -0.0),
 ('LotFrontage', 0.0),
 ('LotConfig_Inside', 0.0),
 ('LotConfig_FR3', -0.0006256165013386384),
 ('LotConfig_FR2', -0.0027079516383723863),
 ('LotConfig_CulDSac', 0.02476617609676854),
 ('LotConfig_Corner', -0.0),
 ('LotArea', 0.04734032850914316),
 ('LandSlope_Sev', -0.0),
 ('LandSlope_Mod', 0.0044928831766734055),
 ('LandSlope_Gtl', -0.0),
 ('LandContour_Lvl', 0.0),
 ('LandContour_Low', 0.0),
 ('LandContour_HLS', 0.017725254349501247),
 ('LandContour_Bnk', -0.004787696053035018),
 ('KitchenQual_TA', -0.018756625933630387),
 ('KitchenQual_Gd', 0.0),
 ('KitchenQual_Fa', 0.0),
 ('KitchenQual_Ex', 0.07969413906343724),
 ('KitchenAbvGr', -0.02038044065308706),
 ('HouseStyle_SLvl', -0.0),
 ('HouseStyle_SFoyer', -1.4156395754590316e-05),
 ('HouseStyle_2Story', -0.0),
 ('HouseStyle_2.5Unf', -0.0),
 ('HouseStyle_2.5Fin', -0.0),
 ('HouseStyle_1Story', 0.0),
 ('HouseStyle_1.5Unf', 0.0),
 ('HouseStyle_1.5Fin', -0.0),
 ('Heating_Wall', 0.0),
 ('Heating_OthW', -0.00973460136757695),
 ('Heating_Grav', -0.0),
 ('Heating_GasW', 0.0),
 ('Heating_GasA', -0.0),
 ('Heating_Floor', 0.0),
 ('HeatingQC_TA', -0.0),
 ('HeatingQC_Po', 0.0),
 ('HeatingQC_Gd', -0.009620771885381863),
 ('HeatingQC_Fa', -0.0),
 ('HeatingQC_Ex', 0.016227863148969165),
 ('HalfBath', 0.0),
 ('GrLivArea', 0.33909550434204677),
 ('GarageYrBlt', -0.0),
 ('GarageType_None', 0.0032246955136905793),
 ('GarageType_Detchd', -0.0),
 ('GarageType_CarPort', -0.0),
 ('GarageType_BuiltIn', 0.0020907713734879645),
 ('GarageType_Basment', -0.0),
 ('GarageType_Attchd', 0.0),
 ('GarageType_2Types', -0.008880080055551765),
 ('GarageQual_TA', -0.0),
 ('GarageQual_Po', -0.0),
 ('GarageQual_None', 1.8099365913168537e-05),
 ('GarageQual_Gd', 0.0),
 ('GarageQual_Fa', -0.0030244808036457),
 ('GarageQual_Ex', 0.018557382407860635),
 ('GarageFinish_Unf', -0.0),
 ('GarageFinish_RFn', -0.0),
 ('GarageFinish_None', 6.975647862484997e-17),
 ('GarageFinish_Fin', 0.0),
 ('GarageCond_TA', -0.0),
 ('GarageCond_Po', -0.0),
 ('GarageCond_None', 4.076380748997879e-05),
 ('GarageCond_Gd', -0.0),
 ('GarageCond_Fa', -0.0),
 ('GarageCond_Ex', -0.0009301689077564168),
 ('GarageCars', 0.02194999078969874),
 ('GarageArea', 0.05569814511096184),
 ('Functional_Typ', 0.03921539537410688),
 ('Functional_Sev', -0.012958411411167294),
 ('Functional_Mod', -0.0),
 ('Functional_Min2', -0.0),
 ('Functional_Min1', -0.0),
 ('Functional_Maj2', -0.0),
 ('Functional_Maj1', -0.0),
 ('FullBath', 0.009605445704171807),
 ('Foundation_Wood', -0.002534060885262043),
 ('Foundation_Stone', 0.0),
 ('Foundation_Slab', 0.0),
 ('Foundation_PConc', 0.01102434139713655),
 ('Foundation_CBlock', -0.0),
 ('Foundation_BrkTil', -0.0),
 ('Fireplaces', 0.03136257363461826),
 ('FireplaceQu_TA', 0.0),
 ('FireplaceQu_Po', -0.0),
 ('FireplaceQu_None', -0.0),
 ('FireplaceQu_Gd', 0.0),
 ('FireplaceQu_Fa', -0.0),
 ('FireplaceQu_Ex', -0.0),
 ('Fence_None', 0.0),
 ('Fence_MnWw', -0.0),
 ('Fence_MnPrv', 0.0),
 ('Fence_GdWo', -0.0),
 ('Fence_GdPrv', -0.004661437986644037),
 ('Exterior2nd_Wd Shng', -0.0),
 ('Exterior2nd_Wd Sdng', 0.0),
 ('Exterior2nd_VinylSd', 0.0),
 ('Exterior2nd_Stucco', -0.0),
 ('Exterior2nd_Stone', -0.0),
 ('Exterior2nd_Plywood', -0.006608165656494486),
 ('Exterior2nd_Other', -0.0),
 ('Exterior2nd_MetalSd', -0.0),
 ('Exterior2nd_ImStucc', 0.01056798031076711),
 ('Exterior2nd_HdBoard', -0.0),
 ('Exterior2nd_CmentBd', 0.0),
 ('Exterior2nd_CBlock', -0.0),
 ('Exterior2nd_BrkFace', 0.0),
 ('Exterior2nd_Brk Cmn', 0.0),
 ('Exterior2nd_AsphShn', 0.0),
 ('Exterior2nd_AsbShng', -0.0),
 ('Exterior1st_WdShing', -0.0),
 ('Exterior1st_Wd Sdng', 0.0),
 ('Exterior1st_VinylSd', 0.0),
 ('Exterior1st_Stucco', -0.0),
 ('Exterior1st_Stone', 0.0),
 ('Exterior1st_Plywood', -0.0),
 ('Exterior1st_MetalSd', 0.0),
 ('Exterior1st_ImStucc', -0.0),
 ('Exterior1st_HdBoard', -0.0),
 ('Exterior1st_CemntBd', 0.0022264289110484623),
 ('Exterior1st_CBlock', -0.0),
 ('Exterior1st_BrkFace', 0.03987991052533993),
 ('Exterior1st_BrkComm', -0.0),
 ('Exterior1st_AsphShn', -0.0),
 ('Exterior1st_AsbShng', 0.0),
 ('ExterQual_TA', -0.012776736466155528),
 ('ExterQual_Gd', 0.0),
 ('ExterQual_Fa', 0.0),
 ('ExterQual_Ex', 0.04913430926233758),
 ('ExterCond_TA', 0.0),
 ('ExterCond_Po', -0.0),
 ('ExterCond_Gd', -0.0),
 ('ExterCond_Fa', 0.0),
 ('ExterCond_Ex', 0.0),
 ('EnclosedPorch', -0.0032411009248082155),
 ('Electrical_SBrkr', 0.0),
 ('Electrical_Mix', 0.0),
 ('Electrical_FuseP', 0.0),
 ('Electrical_FuseF', -0.0),
 ('Electrical_FuseA', -0.0),
 ('Condition2_RRNn', 0.0),
 ('Condition2_RRAn', -0.0),
 ('Condition2_RRAe', -0.0),
 ('Condition2_PosN', -0.10180983216576298),
 ('Condition2_PosA', 0.0),
 ('Condition2_Norm', 0.0),
 ('Condition2_Feedr', -0.0),
 ('Condition2_Artery', 0.0),
 ('Condition1_RRNn', -0.0),
 ('Condition1_RRNe', 0.0),
 ('Condition1_RRAn', 0.0),
 ('Condition1_RRAe', -0.0070618592671596175),
 ('Condition1_PosN', -0.0),
 ('Condition1_PosA', -0.0),
 ('Condition1_Norm', 0.02578146326315433),
 ('Condition1_Feedr', -0.0),
 ('Condition1_Artery', -0.008230080487228852),
 ('CentralAir_Y', 0.0),
 ('CentralAir_N', -0.0),
 ('BsmtUnfSF', -0.0),
 ('BsmtQual_TA', -0.011525711878565135),
 ('BsmtQual_None', 0.0),
 ('BsmtQual_Gd', 0.0),
 ('BsmtQual_Fa', 0.0),
 ('BsmtQual_Ex', 0.09070811930724945),
 ('BsmtHalfBath', -0.0037491411761661777),
 ('BsmtFullBath', 0.014135293707533319),
 ('BsmtFinType2_Unf', 0.0),
 ('BsmtFinType2_Rec', 0.0),
 ('BsmtFinType2_None', 0.0),
 ('BsmtFinType2_LwQ', -0.001830366334178825),
 ('BsmtFinType2_GLQ', 0.0),
 ('BsmtFinType2_BLQ', -0.0011199289785518696),
 ('BsmtFinType2_ALQ', 0.004942204001549737),
 ('BsmtFinType1_Unf', -0.0),
 ('BsmtFinType1_Rec', -0.0),
 ('BsmtFinType1_None', 0.0),
 ('BsmtFinType1_LwQ', -0.0018326830365498756),
 ('BsmtFinType1_GLQ', 0.006175988031093413),
 ('BsmtFinType1_BLQ', -0.0),
 ('BsmtFinType1_ALQ', 0.0),
 ('BsmtFinSF2', 0.0),
 ('BsmtFinSF1', 0.08273511150790007),
 ('BsmtExposure_None', 0.0),
 ('BsmtExposure_No', -0.025997624063453465),
 ('BsmtExposure_Mn', 0.0),
 ('BsmtExposure_Gd', 0.05052529402288771),
 ('BsmtExposure_Av', 0.0),
 ('BsmtCond_TA', 0.0),
 ('BsmtCond_Po', 0.0),
 ('BsmtCond_None', 0.0),
 ('BsmtCond_Gd', -0.001546719918062563),
 ('BsmtCond_Fa', -0.011264921536583265),
 ('BldgType_TwnhsE', -0.0),
 ('BldgType_Twnhs', -0.000802722524523434),
 ('BldgType_Duplex', -0.0020742908237417466),
 ('BldgType_2fmCon', 0.0),
 ('BldgType_1Fam', 0.054394780633208954),
 ('BedroomAbvGr', -0.0),
 ('Alley_Pave', 0.0),
 ('Alley_None', 0.0),
 ('Alley_Grvl', -0.0),
 ('3SsnPorch', 0.00535031738250875),
 ('2ndFlrSF', 0.0),
 ('1stFlrSF', 0.0)]

In [21]:
# Turning variables and their scores into a dataframe to evaluate
var_df = pd.DataFrame(lasso_scores)
var_df

                0         1
0          YrSold  0.000000
1    YearRemodAdd  0.030861
2       YearBuilt  0.089346
3      WoodDeckSF  0.019226
4     TotalBsmtSF  0.083402
..            ...       ...
295    Alley_None  0.000000
296    Alley_Grvl -0.000000
297     3SsnPorch  0.005350
298      2ndFlrSF  0.000000
299      1stFlrSF  0.000000

[300 rows x 2 columns]

In [22]:
# Renaming columns
var_df.columns=["variables","coefficients"]

In [23]:
var_df

        variables  coefficients
0          YrSold      0.000000
1    YearRemodAdd      0.030861
2       YearBuilt      0.089346
3      WoodDeckSF      0.019226
4     TotalBsmtSF      0.083402
..            ...           ...
295    Alley_None      0.000000
296    Alley_Grvl     -0.000000
297     3SsnPorch      0.005350
298      2ndFlrSF      0.000000
299      1stFlrSF      0.000000

[300 rows x 2 columns]

In [24]:
# Taking absolute value of coefficients
var_df['coefficients'] = abs(var_df['coefficients'])
var_df

        variables  coefficients
0          YrSold      0.000000
1    YearRemodAdd      0.030861
2       YearBuilt      0.089346
3      WoodDeckSF      0.019226
4     TotalBsmtSF      0.083402
..            ...           ...
295    Alley_None      0.000000
296    Alley_Grvl      0.000000
297     3SsnPorch      0.005350
298      2ndFlrSF      0.000000
299      1stFlrSF      0.000000

[300 rows x 2 columns]

In [25]:
# Sorting absolute value of coefficients
lasso_sorted = var_df.sort_values(by="coefficients",ascending=False)
top_10 = lasso_sorted.head(10)
top_10
# GrLivArea: living area square feet (above ground)
# RoofMatl_ClyTile: Clay or Tile roof material
# OverallQual: Rating of overall material and finish of the house
# Condition2_PosN: Near to positive off-site feature (park, greenbelt, etc.)
# BsmtQual_Ex: height of the basement (100+ inches)
# YearBuilt: Original construction date
# TotalBsmtSF: Total square feet of basement area
# BsmtFinSF1: Rating of basement finished area's squared feet
# KitchenQual_Ex: Excellent Kitchen quality
# Neighborhood_NoRidge: Northridge neighborhood

                variables  coefficients
136             GrLivArea      0.339096
37       RoofMatl_ClyTile      0.211141
46            OverallQual      0.141465
238       Condition2_PosN      0.101810
259           BsmtQual_Ex      0.090708
2               YearBuilt      0.089346
4             TotalBsmtSF      0.083402
277            BsmtFinSF1      0.082735
114        KitchenQual_Ex      0.079694
58   Neighborhood_NoRidge      0.070848

In [26]:
# Labeling index to match columns in tableau
lasso_sorted.rename_axis(index='Id', inplace=True)
lasso_sorted

              variables  coefficients
Id
136           GrLivArea      0.339096
37     RoofMatl_ClyTile      0.211141
46          OverallQual      0.141465
238     Condition2_PosN      0.101810
259         BsmtQual_Ex      0.090708
..                  ...           ...
135            HalfBath      0.000000
137         GarageYrBlt      0.000000
139   GarageType_Detchd      0.000000
140  GarageType_CarPort      0.000000
299            1stFlrSF      0.000000

[300 rows x 2 columns]

In [27]:
# Saving to csv for tableau
lasso_sorted.to_csv('Output/variables.csv', index = True)

In [28]:
# Retraining from original data but with top 3 variables only
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)
x_train_final = x_train[['GrLivArea', 'OverallQual', 'YearBuilt']]
x_test_final = x_test[['GrLivArea', 'OverallQual', 'YearBuilt']]
# Creating scaler
x_scaler_final = StandardScaler().fit(x_train_final)
# Transforming with scaler
x_train_final_scaled = x_scaler_final.transform(x_train_final)
x_test_final_scaled = x_scaler_final.transform(x_test_final)

In [29]:
# Lasso is slightly better than Elastic Net so it will be chosen to continue
x_train_2 = pd.DataFrame(x_train_scaled)
x_test_2 = pd.DataFrame(x_test_scaled)

In [30]:
# Narrowing down to top 3 variables for user
# Training lasso linear regression model
lasso2 = Lasso(alpha=.01).fit(x_train_final, y_train_scaled)
# Making predictions on test portion
predictions2 = lasso2.predict(x_test_final)
MSE2 = mean_squared_error(y_test_scaled, predictions2)
r2_las2 = lasso2.score(x_test_final, y_test_scaled)
print(f"Lasso Mean Squared Error: {MSE2}, Lasso Score: {r2_las2}")

Lasso Mean Squared Error: 0.2787217461529849, Lasso Score: 0.7584340996462217

In [31]:
# Saving model to disk
pickle.dump(lasso2, open('model.pkl','wb'))
pickle.dump(x_scaler, open('x_scaler.pkl', 'wb'))
pickle.dump(y_scaler, open('y_scaler.pkl', 'wb'))